- name: copying the files to object servers
  copy: src={{ item.src}} dest={{ item.dest}}
  with_items:
    - { src: 'scripts/triggers.sh', dest: '/home/rahul/triggers.sh' }
    - { src: 'triggers/super.sql', dest: '/opt/IBM/tivoli/netcool/omnibus/tmp' }

- name: Granting permission to execute the triggers
  command: chmod 777 /home/rahul/triggers.sh

- name: Deploying object server triggers
  command: /home/rahul/triggers.sh


